# permissions for end users to view applicationtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationtest-viewer-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests/status
  verbs:
  - get
