# permissions for end users to edit applicationtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationtest-editor-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests/status
  verbs:
  - get
