# permissions for end users to view grids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grid-viewer-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids/status
  verbs:
  - get
