# permissions for end users to edit grids.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grid-editor-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids/status
  verbs:
  - get
