
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests/finalizers
  verbs:
  - update
- apiGroups:
  - kgrid.replicated.com
  resources:
  - applicationtests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids/finalizers
  verbs:
  - update
- apiGroups:
  - kgrid.replicated.com
  resources:
  - grids/status
  verbs:
  - get
  - patch
  - update
