# permissions for end users to edit tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-editor-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - tests/status
  verbs:
  - get
