# permissions for end users to edit versions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: version-editor-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - versions/status
  verbs:
  - get
