# permissions for end users to view versions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: version-viewer-role
rules:
- apiGroups:
  - kgrid.replicated.com
  resources:
  - versions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kgrid.replicated.com
  resources:
  - versions/status
  verbs:
  - get
