apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kgrid.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Application is the Schema for the applications API
      displayName: Application
      kind: Application
      name: applications.kgrid.replicated.com
      version: v1alpha1
    - description: Grid is the Schema for the grids API
      displayName: Grid
      kind: Grid
      name: grids.kgrid.replicated.com
      version: v1alpha1
  description: kgrid
  displayName: kgrid
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - testing
  links:
  - name: Kgrid
    url: https://kgrid.domain
  maintainers:
  - email: support@replicated.com
    name: support
  maturity: alpha
  provider:
    name: Replicated, Inc
    url: https://www.replicated.com
  version: 0.0.0
