## Append samples you want in your CSV to this file as resources ##
resources:
- kgrid_v1alpha1_application.yaml
- kgrid_v1alpha1_grid.yaml
- kgrid_v1alpha1_test.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
