name: build-test

on:
  push:
    branches:
      - "**"

jobs:
  build-kots:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16.3'


      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions/checkout@v2


      - run: make test build
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: manager
          path: bin/manager


      - run: make test-kgird kgrid
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: kgrid
          path: bin/kgrid


      - name: build manager image
        uses: docker/build-push-action@v2.5.0
        with:
          tags: kgrid-manager:${{ github.run_id }}
          context: .
          file: Dockerfile.manager
          push: false
      - name: scan manager for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: kgrid-manager:${{ github.run_id }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'


      - name: build kgird image
        uses: docker/build-push-action@v2.5.0
        with:
          tags: kgrid:${{ github.run_id }}
          context: .
          file: Dockerfile.kgrid
          push: false
      - name: scan kgrid for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ttl.sh/automated-${{ github.run_id }}/kotsadm-operator:2h
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
